"""add error_details to strategy_executions

Revision ID: 27d5a57729ac
Revises: 04d10845bc81
Create Date: 2025-11-08 10:38:28.868988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27d5a57729ac'
down_revision: Union[str, Sequence[str], None] = '04d10845bc81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_executions', 'confidence',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               comment='置信度: 0.00 ~ 1.00 (AI对自己分析的可靠性评估)',
               existing_comment='置信度: 0.00 ~ 1.00',
               existing_nullable=False)
    op.alter_column('agent_executions', 'score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='投资建议分数: -100.00 ~ +100.00 (客观投资建议强度)',
               existing_comment='分数: -1.00 ~ +1.00 (可选)',
               existing_nullable=False)
    op.alter_column('portfolios', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('strategy_executions', sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='详细错误信息（包含失败的agent、重试次数等）'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategy_executions', 'error_details')
    op.alter_column('portfolios', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_executions', 'score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='分数: -1.00 ~ +1.00 (可选)',
               existing_comment='投资建议分数: -100.00 ~ +100.00 (客观投资建议强度)',
               existing_nullable=False)
    op.alter_column('agent_executions', 'confidence',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               comment='置信度: 0.00 ~ 1.00',
               existing_comment='置信度: 0.00 ~ 1.00 (AI对自己分析的可靠性评估)',
               existing_nullable=False)
    # ### end Alembic commands ###
