"""Add role field to User model

Revision ID: 45a7e756d0a8
Revises: 75222f346b27
Create Date: 2025-11-06 18:53:57.233594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45a7e756d0a8'
down_revision: Union[str, Sequence[str], None] = '75222f346b27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_executions', 'agent_name',
               existing_type=sa.VARCHAR(length=50),
               comment='Agent名称: macro_agent, ta_agent, onchain_agent',
               existing_nullable=False)
    op.alter_column('agent_executions', 'agent_display_name',
               existing_type=sa.VARCHAR(length=100),
               comment='显示名称: The Oracle, Momentum Scout, Data Warden',
               existing_nullable=True)
    op.alter_column('agent_executions', 'executed_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='执行时间',
               existing_nullable=False)
    op.alter_column('agent_executions', 'execution_duration_ms',
               existing_type=sa.INTEGER(),
               comment='执行耗时（毫秒）',
               existing_nullable=True)
    op.alter_column('agent_executions', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='执行状态: success, failed, timeout',
               existing_nullable=True,
               existing_server_default=sa.text("'success'::character varying"))
    op.alter_column('agent_executions', 'signal',
               existing_type=sa.VARCHAR(length=20),
               comment='信号: BULLISH, BEARISH, NEUTRAL',
               existing_nullable=False)
    op.alter_column('agent_executions', 'confidence',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               comment='置信度: 0.00 ~ 1.00',
               existing_nullable=False)
    op.alter_column('agent_executions', 'score',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               comment='分数: -1.00 ~ +1.00 (可选)',
               existing_nullable=True)
    op.alter_column('agent_executions', 'reasoning',
               existing_type=sa.TEXT(),
               comment='LLM推理过程',
               existing_nullable=False)
    op.alter_column('agent_executions', 'agent_specific_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Agent专属数据: MacroAgent: {etf_flow, fed_rate, ...}, TAAgent: {ema_21, rsi_14, ...}, OnChainAgent: {mvrv, nvt, ...}',
               existing_nullable=False)
    op.alter_column('agent_executions', 'market_data_snapshot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='执行时的完整市场数据（用于复现分析）',
               existing_nullable=True)
    op.alter_column('agent_executions', 'llm_provider',
               existing_type=sa.VARCHAR(length=50),
               comment='LLM供应商: tuzi, openrouter',
               existing_nullable=True)
    op.alter_column('agent_executions', 'llm_model',
               existing_type=sa.VARCHAR(length=100),
               comment='LLM模型: claude-sonnet-4-5-thinking-all',
               existing_nullable=True)
    op.alter_column('agent_executions', 'llm_prompt',
               existing_type=sa.TEXT(),
               comment='发送给LLM的完整prompt',
               existing_nullable=True)
    op.alter_column('agent_executions', 'llm_response',
               existing_type=sa.TEXT(),
               comment='LLM原始响应',
               existing_nullable=True)
    op.alter_column('agent_executions', 'tokens_used',
               existing_type=sa.INTEGER(),
               comment='Token消耗',
               existing_nullable=True)
    op.alter_column('agent_executions', 'llm_cost',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               comment='LLM调用成本（USD）',
               existing_nullable=True)
    op.alter_column('agent_executions', 'caller_type',
               existing_type=sa.VARCHAR(length=50),
               comment='调用方类型: research_chat, strategy_system, manual, NULL',
               existing_nullable=True)
    op.alter_column('agent_executions', 'caller_id',
               existing_type=sa.UUID(),
               comment='调用方ID: conversation_id (可为NULL)',
               existing_nullable=True)
    op.alter_column('agent_executions', 'strategy_execution_id',
               existing_type=sa.UUID(),
               comment='策略执行ID (可为NULL) - 策略系统的强关联',
               existing_nullable=True)
    op.alter_column('agent_executions', 'user_id',
               existing_type=sa.INTEGER(),
               comment='触发用户（可为NULL，如定时任务）',
               existing_nullable=True)
    op.alter_column('agent_executions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_agent_executions_llm'), table_name='agent_executions')
    op.drop_index(op.f('idx_agent_executions_time'), table_name='agent_executions')
    op.drop_index(op.f('idx_agent_executions_user'), table_name='agent_executions')
    op.drop_index(op.f('idx_agent_executions_caller'), table_name='agent_executions')
    op.create_index('idx_agent_executions_caller', 'agent_executions', ['caller_type', 'caller_id', 'executed_at'], unique=False)
    op.drop_index(op.f('idx_agent_executions_latest'), table_name='agent_executions', postgresql_where="((status)::text = 'success'::text)")
    op.create_index('idx_agent_executions_latest', 'agent_executions', ['agent_name', 'executed_at'], unique=False, postgresql_where=sa.text("status = 'success'"))
    op.create_index(op.f('ix_agent_executions_agent_name'), 'agent_executions', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_executions_caller_id'), 'agent_executions', ['caller_id'], unique=False)
    op.create_index(op.f('ix_agent_executions_caller_type'), 'agent_executions', ['caller_type'], unique=False)
    op.create_index(op.f('ix_agent_executions_executed_at'), 'agent_executions', ['executed_at'], unique=False)
    op.drop_constraint(op.f('fk_agent_executions_strategy_execution_id'), 'agent_executions', type_='foreignkey')
    op.create_foreign_key(None, 'agent_executions', 'strategy_executions', ['strategy_execution_id'], ['id'])
    op.drop_index(op.f('idx_snapshots_portfolio_time'), table_name='portfolio_snapshots')
    op.create_index('idx_snapshots_portfolio_time', 'portfolio_snapshots', ['portfolio_id', 'snapshot_time'], unique=False)
    op.create_index(op.f('ix_portfolio_snapshots_snapshot_time'), 'portfolio_snapshots', ['snapshot_time'], unique=False)
    op.drop_index(op.f('idx_executions_status'), table_name='strategy_executions')
    op.drop_index(op.f('idx_executions_strategy'), table_name='strategy_executions')
    op.drop_index(op.f('idx_executions_user_time'), table_name='strategy_executions')
    op.create_index('idx_executions_user_time', 'strategy_executions', ['user_id', 'execution_time'], unique=False)
    op.create_index(op.f('ix_strategy_executions_execution_time'), 'strategy_executions', ['execution_time'], unique=False)
    op.create_index(op.f('ix_strategy_executions_status'), 'strategy_executions', ['status'], unique=False)
    op.create_index(op.f('ix_strategy_executions_strategy_name'), 'strategy_executions', ['strategy_name'], unique=False)
    op.drop_index(op.f('idx_trades_portfolio'), table_name='trades')
    op.create_index('idx_trades_portfolio', 'trades', ['portfolio_id', 'executed_at'], unique=False)
    op.drop_index(op.f('idx_trades_symbol'), table_name='trades')
    op.create_index('idx_trades_symbol', 'trades', ['symbol', 'executed_at'], unique=False)
    op.drop_index(op.f('idx_trades_type'), table_name='trades')
    op.create_index('idx_trades_type', 'trades', ['trade_type', 'executed_at'], unique=False)
    op.create_index(op.f('ix_trades_executed_at'), 'trades', ['executed_at'], unique=False)
    op.create_index(op.f('ix_trades_symbol'), 'trades', ['symbol'], unique=False)
    op.create_index(op.f('ix_trades_trade_type'), 'trades', ['trade_type'], unique=False)

    # Add role column in two steps to handle existing data
    # Step 1: Add nullable column with default
    op.add_column('user', sa.Column('role', sa.String(length=20), nullable=True, server_default='user'))
    # Step 2: Update existing NULL values and make it NOT NULL
    op.execute("UPDATE \"user\" SET role = 'user' WHERE role IS NULL")
    op.alter_column('user', 'role', nullable=False, server_default=None)

    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_column('user', 'role')
    op.drop_index(op.f('ix_trades_trade_type'), table_name='trades')
    op.drop_index(op.f('ix_trades_symbol'), table_name='trades')
    op.drop_index(op.f('ix_trades_executed_at'), table_name='trades')
    op.drop_index('idx_trades_type', table_name='trades')
    op.create_index(op.f('idx_trades_type'), 'trades', ['trade_type', sa.literal_column('executed_at DESC')], unique=False)
    op.drop_index('idx_trades_symbol', table_name='trades')
    op.create_index(op.f('idx_trades_symbol'), 'trades', ['symbol', sa.literal_column('executed_at DESC')], unique=False)
    op.drop_index('idx_trades_portfolio', table_name='trades')
    op.create_index(op.f('idx_trades_portfolio'), 'trades', ['portfolio_id', sa.literal_column('executed_at DESC')], unique=False)
    op.drop_index(op.f('ix_strategy_executions_strategy_name'), table_name='strategy_executions')
    op.drop_index(op.f('ix_strategy_executions_status'), table_name='strategy_executions')
    op.drop_index(op.f('ix_strategy_executions_execution_time'), table_name='strategy_executions')
    op.drop_index('idx_executions_user_time', table_name='strategy_executions')
    op.create_index(op.f('idx_executions_user_time'), 'strategy_executions', ['user_id', sa.literal_column('execution_time DESC')], unique=False)
    op.create_index(op.f('idx_executions_strategy'), 'strategy_executions', ['strategy_name', sa.literal_column('execution_time DESC')], unique=False)
    op.create_index(op.f('idx_executions_status'), 'strategy_executions', ['status'], unique=False)
    op.drop_index(op.f('ix_portfolio_snapshots_snapshot_time'), table_name='portfolio_snapshots')
    op.drop_index('idx_snapshots_portfolio_time', table_name='portfolio_snapshots')
    op.create_index(op.f('idx_snapshots_portfolio_time'), 'portfolio_snapshots', ['portfolio_id', sa.literal_column('snapshot_time DESC')], unique=False)
    op.drop_constraint(None, 'agent_executions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_agent_executions_strategy_execution_id'), 'agent_executions', 'strategy_executions', ['strategy_execution_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_agent_executions_executed_at'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_caller_type'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_caller_id'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_agent_name'), table_name='agent_executions')
    op.drop_index('idx_agent_executions_latest', table_name='agent_executions', postgresql_where=sa.text("status = 'success'"))
    op.create_index(op.f('idx_agent_executions_latest'), 'agent_executions', ['agent_name', sa.literal_column('executed_at DESC')], unique=False, postgresql_where="((status)::text = 'success'::text)")
    op.drop_index('idx_agent_executions_caller', table_name='agent_executions')
    op.create_index(op.f('idx_agent_executions_caller'), 'agent_executions', ['caller_type', 'caller_id', sa.literal_column('executed_at DESC')], unique=False)
    op.create_index(op.f('idx_agent_executions_user'), 'agent_executions', ['user_id', sa.literal_column('executed_at DESC')], unique=False)
    op.create_index(op.f('idx_agent_executions_time'), 'agent_executions', [sa.literal_column('executed_at DESC')], unique=False)
    op.create_index(op.f('idx_agent_executions_llm'), 'agent_executions', ['llm_provider', 'llm_model', sa.literal_column('executed_at DESC')], unique=False)
    op.alter_column('agent_executions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_executions', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='触发用户（可为NULL，如定时任务）',
               existing_nullable=True)
    op.alter_column('agent_executions', 'strategy_execution_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='策略执行ID (可为NULL) - 策略系统的强关联',
               existing_nullable=True)
    op.alter_column('agent_executions', 'caller_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='调用方ID: conversation_id (可为NULL)',
               existing_nullable=True)
    op.alter_column('agent_executions', 'caller_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='调用方类型: research_chat, strategy_system, manual, NULL',
               existing_nullable=True)
    op.alter_column('agent_executions', 'llm_cost',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               comment=None,
               existing_comment='LLM调用成本（USD）',
               existing_nullable=True)
    op.alter_column('agent_executions', 'tokens_used',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Token消耗',
               existing_nullable=True)
    op.alter_column('agent_executions', 'llm_response',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='LLM原始响应',
               existing_nullable=True)
    op.alter_column('agent_executions', 'llm_prompt',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='发送给LLM的完整prompt',
               existing_nullable=True)
    op.alter_column('agent_executions', 'llm_model',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='LLM模型: claude-sonnet-4-5-thinking-all',
               existing_nullable=True)
    op.alter_column('agent_executions', 'llm_provider',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='LLM供应商: tuzi, openrouter',
               existing_nullable=True)
    op.alter_column('agent_executions', 'market_data_snapshot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='执行时的完整市场数据（用于复现分析）',
               existing_nullable=True)
    op.alter_column('agent_executions', 'agent_specific_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Agent专属数据: MacroAgent: {etf_flow, fed_rate, ...}, TAAgent: {ema_21, rsi_14, ...}, OnChainAgent: {mvrv, nvt, ...}',
               existing_nullable=False)
    op.alter_column('agent_executions', 'reasoning',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='LLM推理过程',
               existing_nullable=False)
    op.alter_column('agent_executions', 'score',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               comment=None,
               existing_comment='分数: -1.00 ~ +1.00 (可选)',
               existing_nullable=True)
    op.alter_column('agent_executions', 'confidence',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               comment=None,
               existing_comment='置信度: 0.00 ~ 1.00',
               existing_nullable=False)
    op.alter_column('agent_executions', 'signal',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='信号: BULLISH, BEARISH, NEUTRAL',
               existing_nullable=False)
    op.alter_column('agent_executions', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='执行状态: success, failed, timeout',
               existing_nullable=True,
               existing_server_default=sa.text("'success'::character varying"))
    op.alter_column('agent_executions', 'execution_duration_ms',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='执行耗时（毫秒）',
               existing_nullable=True)
    op.alter_column('agent_executions', 'executed_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='执行时间',
               existing_nullable=False)
    op.alter_column('agent_executions', 'agent_display_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='显示名称: The Oracle, Momentum Scout, Data Warden',
               existing_nullable=True)
    op.alter_column('agent_executions', 'agent_name',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Agent名称: macro_agent, ta_agent, onchain_agent',
               existing_nullable=False)
    # ### end Alembic commands ###
