"""add_system_error_tracking_table

Revision ID: 6b35b1d544f8
Revises: 6d0e12b6144d
Create Date: 2025-11-13 22:37:26.309253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b35b1d544f8'
down_revision: Union[str, Sequence[str], None] = '6d0e12b6144d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_executions', 'template_execution_batch_id',
               existing_type=sa.UUID(),
               comment='批量执行批次ID - 用于关联同一批次的agent和strategy executions',
               existing_comment='批量执行批次ID，用于关联同一批次的agent和strategy executions',
               existing_nullable=True)
    op.drop_index(op.f('idx_agent_executions_batch_id'), table_name='agent_executions')
    op.create_index(op.f('ix_agent_executions_template_execution_batch_id'), 'agent_executions', ['template_execution_batch_id'], unique=False)
    op.alter_column('agent_registry', 'agent_name',
               existing_type=sa.VARCHAR(length=50),
               comment="Agent唯一标识，如 'macro_agent'",
               existing_comment='Agent唯一标识',
               existing_nullable=False)
    op.alter_column('agent_registry', 'display_name',
               existing_type=sa.VARCHAR(length=100),
               comment="显示名称，如 'The Oracle'",
               existing_comment='显示名称',
               existing_nullable=False)
    op.alter_column('agent_registry', 'agent_module',
               existing_type=sa.VARCHAR(length=200),
               comment="Agent模块路径，如 'app.agents.macro_agent'",
               existing_comment='Agent模块路径',
               existing_nullable=False)
    op.alter_column('agent_registry', 'agent_class',
               existing_type=sa.VARCHAR(length=100),
               comment="Agent类名，如 'MacroAgent'",
               existing_comment='Agent类名',
               existing_nullable=False)
    op.alter_column('agent_registry', 'available_tools',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment="Agent可用的Tool列表，如 ['fetch_macro_data', 'fetch_fear_greed']",
               existing_comment='Agent可用的Tool列表',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('api_config', 'api_name',
               existing_type=sa.VARCHAR(length=100),
               comment="API唯一标识，如 'binance_api'",
               existing_comment='API唯一标识',
               existing_nullable=False)
    op.alter_column('api_config', 'display_name',
               existing_type=sa.VARCHAR(length=200),
               comment="显示名称，如 'Binance API'",
               existing_comment='显示名称',
               existing_nullable=False)
    op.alter_column('api_config', 'api_secret_encrypted',
               existing_type=sa.TEXT(),
               comment='加密存储的API密钥Secret（如果需要）',
               existing_comment='加密存储的API密钥Secret',
               existing_nullable=True)
    op.alter_column('portfolios', 'strategy_definition_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='关联的策略模板ID')
    op.alter_column('portfolios', 'instance_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False,
               comment='实例名称，用户自定义',
               existing_comment='实例名称')
    op.alter_column('portfolios', 'instance_description',
               existing_type=sa.TEXT(),
               comment='实例描述，用户可选',
               existing_comment='实例描述',
               existing_nullable=True)
    op.alter_column('portfolios', 'instance_params',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               comment='实例独立参数配置',
               existing_comment='实例参数')
    op.alter_column('portfolios', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('portfolios', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='实例开关',
               existing_nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('portfolios', 'last_execution_time',
               existing_type=postgresql.TIMESTAMP(),
               comment='上次执行时间',
               existing_nullable=True)
    op.alter_column('portfolios', 'consecutive_bullish_count',
               existing_type=sa.INTEGER(),
               comment='当前连续看涨信号次数',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('portfolios', 'consecutive_bullish_since',
               existing_type=postgresql.TIMESTAMP(),
               comment='连续看涨开始时间',
               existing_nullable=True)
    op.alter_column('portfolios', 'consecutive_bearish_count',
               existing_type=sa.INTEGER(),
               comment='当前连续看跌信号次数',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('portfolios', 'consecutive_bearish_since',
               existing_type=postgresql.TIMESTAMP(),
               comment='连续看跌开始时间',
               existing_nullable=True)
    op.alter_column('portfolios', 'last_conviction_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='上次信念分数',
               existing_nullable=True)
    op.create_index(op.f('ix_portfolios_strategy_definition_id'), 'portfolios', ['strategy_definition_id'], unique=False)
    op.alter_column('strategy_definitions', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment="唯一标识，如 'multi_agent_btc_v1'",
               existing_comment='唯一标识，如 multi_agent_btc_v1',
               existing_nullable=False)
    op.alter_column('strategy_definitions', 'display_name',
               existing_type=sa.VARCHAR(length=200),
               comment="显示名称，如 'Multi-Agent BTC Strategy'",
               existing_comment='显示名称，如 Multi-Agent BTC Strategy',
               existing_nullable=False)
    op.alter_column('strategy_definitions', 'decision_agent_module',
               existing_type=sa.VARCHAR(length=200),
               comment="决策Agent模块路径，如 'app.decision_agents.multi_agent_conviction'",
               existing_comment='决策Agent模块路径',
               existing_nullable=False)
    op.alter_column('strategy_definitions', 'decision_agent_class',
               existing_type=sa.VARCHAR(length=100),
               comment="决策Agent类名，如 'MultiAgentConvictionDecision'",
               existing_comment='决策Agent类名',
               existing_nullable=False)
    op.alter_column('strategy_definitions', 'business_agents',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment="业务Agent列表，如 ['macro', 'ta', 'onchain']",
               existing_comment='业务Agent列表',
               existing_nullable=False)
    op.alter_column('strategy_definitions', 'trade_channel',
               existing_type=sa.VARCHAR(length=50),
               comment="交易渠道，如 'binance_spot', 'hyperliquid_perp'",
               existing_comment='交易渠道',
               existing_nullable=False)
    op.alter_column('strategy_definitions', 'trade_symbol',
               existing_type=sa.VARCHAR(length=20),
               comment="交易币种，如 'BTC', 'ETH'",
               existing_comment='交易币种',
               existing_nullable=False)
    op.alter_column('strategy_definitions', 'default_params',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='默认参数配置，包含所有阈值、权重等',
               existing_comment='默认参数配置',
               existing_nullable=False)
    op.alter_column('strategy_executions', 'template_execution_batch_id',
               existing_type=sa.UUID(),
               comment='批量执行批次ID - 用于关联同一批次的agent和strategy executions',
               existing_comment='批量执行批次ID，用于关联同一批次的agent和strategy executions',
               existing_nullable=True)
    op.drop_index(op.f('idx_strategy_executions_batch_id'), table_name='strategy_executions')
    op.create_index(op.f('ix_strategy_executions_template_execution_batch_id'), 'strategy_executions', ['template_execution_batch_id'], unique=False)
    op.alter_column('tool_registry', 'required_apis',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment="Tool依赖的API列表，如 ['fred_api', 'glassnode_api']",
               existing_comment='Tool依赖的API列表',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tool_registry', 'required_apis',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Tool依赖的API列表',
               existing_comment="Tool依赖的API列表，如 ['fred_api', 'glassnode_api']",
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index(op.f('ix_strategy_executions_template_execution_batch_id'), table_name='strategy_executions')
    op.create_index(op.f('idx_strategy_executions_batch_id'), 'strategy_executions', ['template_execution_batch_id'], unique=False)
    op.alter_column('strategy_executions', 'template_execution_batch_id',
               existing_type=sa.UUID(),
               comment='批量执行批次ID，用于关联同一批次的agent和strategy executions',
               existing_comment='批量执行批次ID - 用于关联同一批次的agent和strategy executions',
               existing_nullable=True)
    op.alter_column('strategy_definitions', 'default_params',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='默认参数配置',
               existing_comment='默认参数配置，包含所有阈值、权重等',
               existing_nullable=False)
    op.alter_column('strategy_definitions', 'trade_symbol',
               existing_type=sa.VARCHAR(length=20),
               comment='交易币种',
               existing_comment="交易币种，如 'BTC', 'ETH'",
               existing_nullable=False)
    op.alter_column('strategy_definitions', 'trade_channel',
               existing_type=sa.VARCHAR(length=50),
               comment='交易渠道',
               existing_comment="交易渠道，如 'binance_spot', 'hyperliquid_perp'",
               existing_nullable=False)
    op.alter_column('strategy_definitions', 'business_agents',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='业务Agent列表',
               existing_comment="业务Agent列表，如 ['macro', 'ta', 'onchain']",
               existing_nullable=False)
    op.alter_column('strategy_definitions', 'decision_agent_class',
               existing_type=sa.VARCHAR(length=100),
               comment='决策Agent类名',
               existing_comment="决策Agent类名，如 'MultiAgentConvictionDecision'",
               existing_nullable=False)
    op.alter_column('strategy_definitions', 'decision_agent_module',
               existing_type=sa.VARCHAR(length=200),
               comment='决策Agent模块路径',
               existing_comment="决策Agent模块路径，如 'app.decision_agents.multi_agent_conviction'",
               existing_nullable=False)
    op.alter_column('strategy_definitions', 'display_name',
               existing_type=sa.VARCHAR(length=200),
               comment='显示名称，如 Multi-Agent BTC Strategy',
               existing_comment="显示名称，如 'Multi-Agent BTC Strategy'",
               existing_nullable=False)
    op.alter_column('strategy_definitions', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='唯一标识，如 multi_agent_btc_v1',
               existing_comment="唯一标识，如 'multi_agent_btc_v1'",
               existing_nullable=False)
    op.drop_index(op.f('ix_portfolios_strategy_definition_id'), table_name='portfolios')
    op.alter_column('portfolios', 'last_conviction_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='上次信念分数',
               existing_nullable=True)
    op.alter_column('portfolios', 'consecutive_bearish_since',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='连续看跌开始时间',
               existing_nullable=True)
    op.alter_column('portfolios', 'consecutive_bearish_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='当前连续看跌信号次数',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('portfolios', 'consecutive_bullish_since',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='连续看涨开始时间',
               existing_nullable=True)
    op.alter_column('portfolios', 'consecutive_bullish_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='当前连续看涨信号次数',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('portfolios', 'last_execution_time',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='上次执行时间',
               existing_nullable=True)
    op.alter_column('portfolios', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='实例开关',
               existing_nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('portfolios', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('portfolios', 'instance_params',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               comment='实例参数',
               existing_comment='实例独立参数配置')
    op.alter_column('portfolios', 'instance_description',
               existing_type=sa.TEXT(),
               comment='实例描述',
               existing_comment='实例描述，用户可选',
               existing_nullable=True)
    op.alter_column('portfolios', 'instance_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True,
               comment='实例名称',
               existing_comment='实例名称，用户自定义')
    op.alter_column('portfolios', 'strategy_definition_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='关联的策略模板ID')
    op.alter_column('api_config', 'api_secret_encrypted',
               existing_type=sa.TEXT(),
               comment='加密存储的API密钥Secret',
               existing_comment='加密存储的API密钥Secret（如果需要）',
               existing_nullable=True)
    op.alter_column('api_config', 'display_name',
               existing_type=sa.VARCHAR(length=200),
               comment='显示名称',
               existing_comment="显示名称，如 'Binance API'",
               existing_nullable=False)
    op.alter_column('api_config', 'api_name',
               existing_type=sa.VARCHAR(length=100),
               comment='API唯一标识',
               existing_comment="API唯一标识，如 'binance_api'",
               existing_nullable=False)
    op.alter_column('agent_registry', 'available_tools',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Agent可用的Tool列表',
               existing_comment="Agent可用的Tool列表，如 ['fetch_macro_data', 'fetch_fear_greed']",
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('agent_registry', 'agent_class',
               existing_type=sa.VARCHAR(length=100),
               comment='Agent类名',
               existing_comment="Agent类名，如 'MacroAgent'",
               existing_nullable=False)
    op.alter_column('agent_registry', 'agent_module',
               existing_type=sa.VARCHAR(length=200),
               comment='Agent模块路径',
               existing_comment="Agent模块路径，如 'app.agents.macro_agent'",
               existing_nullable=False)
    op.alter_column('agent_registry', 'display_name',
               existing_type=sa.VARCHAR(length=100),
               comment='显示名称',
               existing_comment="显示名称，如 'The Oracle'",
               existing_nullable=False)
    op.alter_column('agent_registry', 'agent_name',
               existing_type=sa.VARCHAR(length=50),
               comment='Agent唯一标识',
               existing_comment="Agent唯一标识，如 'macro_agent'",
               existing_nullable=False)
    op.drop_index(op.f('ix_agent_executions_template_execution_batch_id'), table_name='agent_executions')
    op.create_index(op.f('idx_agent_executions_batch_id'), 'agent_executions', ['template_execution_batch_id'], unique=False)
    op.alter_column('agent_executions', 'template_execution_batch_id',
               existing_type=sa.UUID(),
               comment='批量执行批次ID，用于关联同一批次的agent和strategy executions',
               existing_comment='批量执行批次ID - 用于关联同一批次的agent和strategy executions',
               existing_nullable=True)
    # ### end Alembic commands ###
