"""add_trading_thresholds_to_portfolio

Revision ID: fddbafdebc9e
Revises: 27d5a57729ac
Create Date: 2025-11-08 11:48:04.119586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fddbafdebc9e'
down_revision: Union[str, Sequence[str], None] = '27d5a57729ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('fg_circuit_breaker_threshold', sa.Integer(), server_default='20', nullable=False))
    op.add_column('portfolios', sa.Column('fg_position_adjust_threshold', sa.Integer(), server_default='30', nullable=False))
    op.add_column('portfolios', sa.Column('buy_threshold', sa.Float(), server_default='50', nullable=False))
    op.add_column('portfolios', sa.Column('partial_sell_threshold', sa.Float(), server_default='50', nullable=False))
    op.add_column('portfolios', sa.Column('full_sell_threshold', sa.Float(), server_default='45', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'full_sell_threshold')
    op.drop_column('portfolios', 'partial_sell_threshold')
    op.drop_column('portfolios', 'buy_threshold')
    op.drop_column('portfolios', 'fg_position_adjust_threshold')
    op.drop_column('portfolios', 'fg_circuit_breaker_threshold')
    # ### end Alembic commands ###
